@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Aug 08 03:48:40 +1000 2025
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim voting_proc_tb_behav -key {Behavioral:sim_1:Functional:voting_proc_tb} -tclbatch voting_proc_tb.tcl -view C:/Users/Admin/Documents/Uni/COMP3211/Assignment/VotingHDL/tag_gen_vivado_project/assignment.srcs/sim_1/imports/project/voting_proc_testbench_behav.wcfg -log simulate.log"
call xsim  voting_proc_tb_behav -key {Behavioral:sim_1:Functional:voting_proc_tb} -tclbatch voting_proc_tb.tcl -view C:/Users/Admin/Documents/Uni/COMP3211/Assignment/VotingHDL/tag_gen_vivado_project/assignment.srcs/sim_1/imports/project/voting_proc_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
